[hub]
GossipPort = 2282
BootstrapPeers = [
  "/dns/lamia.farcaster.xyz/tcp/2283/p2p/12D3KooWJECuSHn5edaorpufE9ceAoqR5zcAuD4ThoyDzVaz77GV"
]
Debug = true
BufferSize = 128
ContactInterval = 30

[handlers.postgresql]
Enabled = true
Params = { DbAddress = "postgres://postgres:example@localhost:5432/postgres" }