[hub]
PublicHubIp = "92.158.95.48"
GossipPort = 2282
RpcPort = 2283
BootstrapPeers = [
  "/dns/hoyt.farcaster.xyz/tcp/2282/p2p/12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo",
  "/dns/lamia.farcaster.xyz/tcp/2282/p2p/12D3KooWJECuSHn5edaorpufE9ceAoqR5zcAuD4ThoyDzVaz77GV",
  "/dns/bootstrap.neynar.com/tcp/2282/p2p/12D3KooWNsC2vzuHdKDfSM6xnMZwMjWK8zZCYHyLXuhRMeVRebGK",
]
Debug = false
BufferSize = 128
ContactInterval = 3000

[handlers.postgresql]
Enabled = true
DbAddress = "postgres://postgres:example@db:5432/postgres"
# refer to the enum l.60 in message.proto for the integer of msg types | here we only want to save the casts
FidsAllowed = [10626]
