services:
  farseer:
    image: noctisatrae/farseer:latest
    restart: always
    ports:
      - 2282
      - 2283
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./config.toml:/usr/src/app/config.toml
      - ./hub_identity:/usr/src/app/hub_identity
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080