[hub]
GossipPort = 2282
BootstrapPeers = [
  "/dns/nemes.farcaster.xyz/tcp/2282/p2p/12D3KooWMQrf6unpGJfLBmTGy3eKTo4cGcXktWRbgMnfbZLXqBbn"
]
Debug = false
BufferSize = 128
ContactInterval = 30

[servers.rpc]
enabled = true

[databases]
redis = {enabled = true}